-- Add public recipe comments and ratings so My Recipes can show counts and averages.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  content text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comments_recipe_id_idx on public.comments (recipe_id);
create index if not exists comments_author_id_idx on public.comments (author_id);

alter table public.comments enable row level security;

create policy "Everyone can read comments"
  on public.comments
  for select
  using (true);

create policy "Users can insert their own comments"
  on public.comments
  for insert
  with check (auth.uid() = author_id);

create policy "Users can update their own comments"
  on public.comments
  for update
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

create policy "Users can delete their own comments"
  on public.comments
  for delete
  using (auth.uid() = author_id);

grant select, insert, update, delete on table public.comments to authenticated;
grant select on table public.comments to anon;