-- Simplified RecipeBox schema
-- Users are handled by Supabase Auth (auth.users)

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  ingredients text not null,
  steps text not null,
  image_url text,
  category_id bigint not null references public.categories (id) on delete restrict,
  owner_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recipes_category_id_idx on public.recipes (category_id);
create index if not exists recipes_owner_id_idx on public.recipes (owner_id);

alter table public.categories enable row level security;
alter table public.recipes enable row level security;

-- Public read access
create policy "Public can read categories"
  on public.categories
  for select
  using (true);

create policy "Public can read recipes"
  on public.recipes
  for select
  using (true);

-- Recipe ownership controls
create policy "Authenticated users can insert their own recipes"
  on public.recipes
  for insert
  with check (auth.uid() = owner_id);

create policy "Users can update their own recipes"
  on public.recipes
  for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "Users can delete their own recipes"
  on public.recipes
  for delete
  using (auth.uid() = owner_id);

-- Table privileges for Supabase API roles
grant select on table public.categories to anon, authenticated;
grant select on table public.recipes to anon, authenticated;
grant insert, update, delete on table public.recipes to authenticated;