-- Add tags and recipe_tags for multi-tag recipes.

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.recipe_tags (
  recipe_id bigint not null references public.recipes (id) on delete cascade,
  tag_id bigint not null references public.tags (id) on delete cascade,
  primary key (recipe_id, tag_id)
);

create index if not exists recipe_tags_recipe_id_idx on public.recipe_tags (recipe_id);
create index if not exists recipe_tags_tag_id_idx on public.recipe_tags (tag_id);

alter table public.tags enable row level security;
alter table public.recipe_tags enable row level security;

drop policy if exists "Public can read tags" on public.tags;
drop policy if exists "Authenticated users can insert tags" on public.tags;
drop policy if exists "Admins can update tags" on public.tags;
drop policy if exists "Admins can delete tags" on public.tags;
drop policy if exists "Public can read recipe tags" on public.recipe_tags;
drop policy if exists "Recipe owners and admins can insert recipe tags" on public.recipe_tags;
drop policy if exists "Recipe owners and admins can delete recipe tags" on public.recipe_tags;

create policy "Public can read tags"
  on public.tags
  for select
  using (true);

create policy "Authenticated users can insert tags"
  on public.tags
  for insert
  with check (auth.role() = 'authenticated');

create policy "Admins can update tags"
  on public.tags
  for update
  using (exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  ))
  with check (exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  ));

create policy "Admins can delete tags"
  on public.tags
  for delete
  using (exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  ));

create policy "Public can read recipe tags"
  on public.recipe_tags
  for select
  using (true);

create policy "Recipe owners and admins can insert recipe tags"
  on public.recipe_tags
  for insert
  with check (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_id
        and (
          r.owner_id = auth.uid()
          or exists (
            select 1
            from public.profiles p
            where p.id = auth.uid()
              and p.role = 'admin'
          )
        )
    )
  );

create policy "Recipe owners and admins can delete recipe tags"
  on public.recipe_tags
  for delete
  using (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_id
        and (
          r.owner_id = auth.uid()
          or exists (
            select 1
            from public.profiles p
            where p.id = auth.uid()
              and p.role = 'admin'
          )
        )
    )
  );

grant select on table public.tags to anon, authenticated;
grant insert on table public.tags to authenticated;
grant select on table public.recipe_tags to anon, authenticated;
grant insert, delete on table public.recipe_tags to authenticated;
